@ECHO OFF
setlocal enabledelayedexpansion

echo // Autogenerated by genmapping_c.bat
echo #include "../includes.h"
echo #include "../funcproto.h"
echo #include ^<time.h^>
echo:

echo int Test_Caller(const char *input){
for /f %%x in ('dir /b /s *.c') do ^
echo     if(streq(input, "%%~nx.c")){ ^

         clock_t start = clock(); ^

         int result = Test_%%~nx(); ^

         clock_t end = clock(); ^

         const char *verdict = result ? "PASS" : "FAIL"; ^

         printf("[%%s] %%s (%%f s)\n", verdict, "%%~nx", ((float)(end-start))/CLOCKS_PER_SEC); ^

         return ^^!result; ^

    }


echo:
echo     printf("[FAIL] %%s not found!\n", input);
echo     return 1;
echo }
echo:

echo int Test_Test_Caller(){
echo     // Nasty side-effect...
echo     return 0;
echo }