// Autogenerated by genmapping_c.bat
#include "../includes.h"
#include "../funcproto.h"
#include <time.h>

int Test_Caller(const char *input){
    if(streq(input, "Test_Caller.c")){ 
         clock_t start = clock(); 
         int result = Test_Test_Caller(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "Test_Caller", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
    if(streq(input, "Eq_Parse_Int_ConstDec.c")){ 
         clock_t start = clock(); 
         int result = Test_Eq_Parse_Int_ConstDec(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "Eq_Parse_Int_ConstDec", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
    if(streq(input, "Eq_Parse_Int_ConstHex.c")){ 
         clock_t start = clock(); 
         int result = Test_Eq_Parse_Int_ConstHex(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "Eq_Parse_Int_ConstHex", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
    if(streq(input, "asprintf_Basic.c")){ 
         clock_t start = clock(); 
         int result = Test_asprintf_Basic(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "asprintf_Basic", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
    if(streq(input, "CRC32_File_Basic.c")){ 
         clock_t start = clock(); 
         int result = Test_CRC32_File_Basic(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "CRC32_File_Basic", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
    if(streq(input, "_InitSeq.c")){ 
         clock_t start = clock(); 
         int result = Test__InitSeq(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "_InitSeq", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
    if(streq(input, "streq.c")){ 
         clock_t start = clock(); 
         int result = Test_streq(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "streq", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }
        if(streq(input, "strieq.c")){ 
         clock_t start = clock(); 
         int result = Test_strieq(); 
         clock_t end = clock(); 
         const char *verdict = result ? "PASS" : "FAIL"; 
         printf("[%s] %s (%f s)\n", verdict, "strieq", ((float)(end-start))/CLOCKS_PER_SEC); 
         return !result; 
    }

    printf("[FAIL] %s not found\n", input);
    return 1;
}

int Test_Test_Caller(){
    // Nasty side-effect...
    return 0;
}
