//Header file for everything
void DeleteAll(void);
void SetPrcsr(const char * a);
void StringStp(char a);
void Tabs(int a);
void Comments(int a);
void Voids(int a);
void XrefShow(int a);
void AutoShow(int a);
void Indent(int a);
void CmtIndent(int a);
void TailDepth(int a);
void SetSelector(int a, int b);
void SegCreate(int a, int b, int c, int d, int e, int f);
void SegRename(int a, const char *b);
void SegClass(int a, const char *b);
void SegDefReg(int a, const char *b, int c);
void SetSegmentType(int a, int b);
void LowVoids(int a);
void HighVoids(int a);
int AddEnum(int a, const char *b, int c);
void AddConstEx(int id, const char *a, int b, int c);
int AddStrucEx(int a, const char *b, int c);
int GetStrucIdByName(const char *a);
void AddStrucMember(int id, const char *a, int b, int c, int d, int e);
void AddStruct(int addr, const char *id);
void MakeStr(int addr, int end);
void MakeStruct(int a, const char *b);
void OpHex(int a, int b);
void OpDecimal(int a, int b);
void OpOctal(int a, int b);
void OpStkvar(int a, int b);
void OpOff(int a, int b, int c);
void ExtLinA(int addr, int a, const char *b);
void MakeRptCmt(int addr, const char *a);
void OpEnumEx(int a, int b, int c, int d);
int GetEnum(const char *a);
void OpSign(int a, int b);
void OpNot(int a, int b);
void SetFunctionFlags(int addr, int flags);
void MakeFrame(int addr, int a, int b, int c);
void MakeLocal(int a, int b, const char *c, const char *d);
enum MakeNameEx_Arg {SN_LOCAL}; //?
void MakeNameEx(int a, const char *b, enum MakeNameEx_Arg c);
void MakeComm(int addr, const char *comment);
void MakeName(int addr, const char *name);
void MakeCode(int addr);
void MakeArray(int addr, int len);
void MakeDword(int addr);
void MakeWord(int addr);
void MakeFloat(int addr);
void MakeDouble(int addr);
void MakeByte(int addr);
void MakeTbyte(int addr);
void MakeFunction(int start, int end);

static GenInfo(void);
static Segments(void);
static Enums(void);
static Structures(void);
static Bytes(void);
static Functions(void);
static SegRegs(void);
int idc_main(void);
