# - find JANSSON
# JANSSON_INCLUDE_DIR - Where to find JANSSON header files (directory)
# JANSSON_LIBRARIES - JANSSON libraries
# JANSSON_LIBRARY_RELEASE - Where the release library is
# JANSSON_LIBRARY_DEBUG - Where the debug library is
# JANSSON_FOUND - Set to TRUE if we found everything (library, includes and executable)

# Copyright (c) 2010 Pau Garcia i Quiles, <pgquiles@elpauer.org>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.
#
# Generated by CModuler, a CMake Module Generator - http://gitorious.org/cmoduler

IF( JANSSON_INCLUDE_DIR AND JANSSON_LIBRARY_RELEASE AND JANSSON_LIBRARY_DEBUG )
    SET(JANSSON_FIND_QUIETLY TRUE)
ENDIF( JANSSON_INCLUDE_DIR AND JANSSON_LIBRARY_RELEASE AND JANSSON_LIBRARY_DEBUG )

FIND_PATH(JANSSON_INCLUDE_DIR jansson.h)

FIND_LIBRARY(JANSSON_LIBRARY_RELEASE NAMES jansson)

FIND_LIBRARY(JANSSON_LIBRARY_DEBUG NAMES jansson janssond HINTS /usr/lib/debug/usr/lib/)

IF( JANSSON_LIBRARY_RELEASE OR JANSSON_LIBRARY_DEBUG AND JANSSON_INCLUDE_DIR )
        SET( JANSSON_FOUND TRUE )
ENDIF( JANSSON_LIBRARY_RELEASE OR JANSSON_LIBRARY_DEBUG AND JANSSON_INCLUDE_DIR )

IF( JANSSON_LIBRARY_DEBUG AND JANSSON_LIBRARY_RELEASE )
        # if the generator supports configuration types then set
        # optimized and debug libraries, or if the CMAKE_BUILD_TYPE has a value
        IF( CMAKE_CONFIGURATION_TYPES OR CMAKE_BUILD_TYPE )
                SET( JANSSON_LIBRARIES optimized ${JANSSON_LIBRARY_RELEASE} debug ${JANSSON_LIBRARY_DEBUG} )
        ELSE( CMAKE_CONFIGURATION_TYPES OR CMAKE_BUILD_TYPE )
    # if there are no configuration types and CMAKE_BUILD_TYPE has no value
    # then just use the release libraries
                SET( JANSSON_LIBRARIES ${JANSSON_LIBRARY_RELEASE} )
        ENDIF( CMAKE_CONFIGURATION_TYPES OR CMAKE_BUILD_TYPE )
ELSEIF( JANSSON_LIBRARY_RELEASE )
        SET( JANSSON_LIBRARIES ${JANSSON_LIBRARY_RELEASE} )
ELSE( JANSSON_LIBRARY_DEBUG AND JANSSON_LIBRARY_RELEASE )
        SET( JANSSON_LIBRARIES ${JANSSON_LIBRARY_DEBUG} )
ENDIF( JANSSON_LIBRARY_DEBUG AND JANSSON_LIBRARY_RELEASE )

IF( JANSSON_FOUND )
        IF( NOT JANSSON_FIND_QUIETLY )
                MESSAGE( STATUS "Found JANSSON header file in ${JANSSON_INCLUDE_DIR}")
                MESSAGE( STATUS "Found JANSSON libraries: ${JANSSON_LIBRARIES}")
        ENDIF( NOT JANSSON_FIND_QUIETLY )
ELSE(JANSSON_FOUND)
        IF( JANSSON_FIND_REQUIRED)
                MESSAGE( FATAL_ERROR "Could not find JANSSON" )
        ELSE( JANSSON_FIND_REQUIRED)
                MESSAGE( STATUS "Optional package JANSSON was not found" )
        ENDIF( JANSSON_FIND_REQUIRED)
ENDIF(JANSSON_FOUND)