// Generated by ResEdit 1.6.4
// Copyright (C) 2006-2015
// http://www.resedit.net

HINSTANCE hInst = GetModuleHandle(0);
WNDCLASSEX wcex;
ZeroMemory(&wcex, sizeof wcex);
wcex.cbSize         = sizeof wcex;
wcex.hbrBackground  = (HBRUSH)(COLOR_3DFACE + 1);
wcex.lpszMenuName   = 0;


HMENU hmenu1 = CreateMenu();
HMENU hmenu1_1 = CreatePopupMenu();
AppendMenu(hmenu1_1, MF_STRING, 0, ("&Load Mod..."));
AppendMenu(hmenu1_1, MF_STRING, 0, ("&Remove Mod..."));
AppendMenu(hmenu1_1, MF_STRING, 0, ("&Create Compilation..."));
AppendMenu(hmenu1_1, MF_SEPARATOR, 0, 0);
AppendMenu(hmenu1_1, MF_STRING, 0, ("Play Sonic R"));
AppendMenu(hmenu1_1, MF_STRING, 0, ("E&xit"));
AppendMenu(hmenu1, MF_STRING | MF_POPUP | MF_MENUBREAK, (UINT_PTR)hmenu1_1, ("File"));
HMENU hmenu1_2 = CreatePopupMenu();
AppendMenu(hmenu1_2, MF_STRING, 0, ("Free EXE &Space..."));
AppendMenu(hmenu1_2, MF_STRING, 0, ("&Directory Structure..."));
AppendMenu(hmenu1, MF_STRING | MF_POPUP | MF_MENUBREAK, (UINT_PTR)hmenu1_2, ("View"));
HMENU hmenu1_3 = CreatePopupMenu();
AppendMenu(hmenu1_3, MF_STRING, 0, ("View Contents..."));
AppendMenu(hmenu1_3, MF_SEPARATOR, 0, 0);
AppendMenu(hmenu1_3, MF_STRING, 0, ("About..."));
AppendMenu(hmenu1, MF_STRING | MF_POPUP | MF_MENUBREAK, (UINT_PTR)hmenu1_3, ("Help"));


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = "WndClass2";
RegisterClassEx(&wcex);

HFONT hfont2 = CreateFont(-11, 0, 0, 0, 0, FALSE, FALSE, FALSE, 1, 0, 0, 0, 0, ("Ms Shell Dlg"));
HWND hwnd = CreateWindowEx(WS_EX_WINDOWEDGE | WS_EX_DLGMODALFRAME, ("WndClass")2, 0, WS_BORDER | WS_VISIBLE | WS_POPUP, 0, 0, 276, 380, 0, 0, hInst, 0);
HWND hCtrl2_0 = CreateWindowEx(0, WC_BUTTON, ("OK"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000001, 185, 340, 75, 23, hwnd, (HMENU)IDOK, hInst, 0);
SendMessage(hCtrl2_0, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl2_1 = CreateWindowEx(0, WC_STATIC, ("©2015 InvisibleUp \r\n\r\nThis program is not affiliated by Sega Corporation, TT Games or any subsidiaries thereof. It is available free of charge under the [INSERT LICENSE HERE] license at http://github.com/InvisibleUp/[URL]/."), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_CENTER, 11, 226, 249, 80, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl2_1, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl2_2 = CreateWindowEx(0, WC_STATIC, ("IDB_BITMAP1"), WS_VISIBLE | WS_CHILD | WS_BORDER | SS_BITMAP | SS_CENTERIMAGE | SS_REALSIZEIMAGE, 11, 11, 249, 210, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl2_2, WM_SETFONT, (WPARAM), FALSE);


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = "WndClass3";
RegisterClassEx(&wcex);

HFONT hfont3 = CreateFont(-11, 0, 0, 0, 0, FALSE, FALSE, FALSE, 1, 0, 0, 0, 0, ("Ms Shell Dlg"));
HWND hwnd = CreateWindowEx(WS_EX_LEFT, ("WndClass")3, ("Disk Space"), WS_CAPTION | WS_VISIBLE | WS_POPUP | WS_SYSMENU, 0, 0, 306, 402, 0, 0, hInst, 0);
HWND hCtrl3_0 = CreateWindowEx(0, WC_BUTTON, ("View Patches"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_DISABLED, 134, 340, 75, 23, hwnd, (HMENU)IDDISKPATCHES, hInst, 0);
SendMessage(hCtrl3_0, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl3_1 = CreateWindowEx(0, WC_TREEVIEW, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | TVS_HASBUTTONS | TVS_HASLINES | TVS_LINESATROOT | TVS_DISABLEDRAGDROP | TVS_INFOTIP | TVS_FULLROWSELECT, 11, 11, 279, 297, hwnd, (HMENU)IDC_DISKLIST, hInst, 0);
SendMessage(hCtrl3_1, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl3_2 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 11, 314, 278, 20, hwnd, (HMENU)IDC_DISKINFO, hInst, 0);
SendMessage(hCtrl3_2, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl3_3 = CreateWindowEx(0, WC_BUTTON, ("OK"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000001, 215, 340, 75, 23, hwnd, (HMENU)IDOK, hInst, 0);
SendMessage(hCtrl3_3, WM_SETFONT, (WPARAM), FALSE);


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = "WndClass4";
RegisterClassEx(&wcex);

HFONT hfont4 = CreateFont(-11, 0, 0, 0, 0, FALSE, FALSE, FALSE, 1, 0, 0, 0, 0, ("Ms Shell Dlg"));
HWND hwnd = CreateWindowEx(WS_EX_CLIENTEDGE | WS_EX_APPWINDOW, ("WndClass")4, ("Sonic R Mod Loader"), WS_CAPTION | WS_VISIBLE | WS_GROUP | WS_POPUP | WS_SYSMENU, 0, 0, 535, 448, 0, 0, hInst, 0);
HWND hCtrl4_0 = CreateWindowEx(0, WC_BUTTON, ("Play Sonic R"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000001, 395, 385, 120, 23, hwnd, (HMENU)IDOK, hInst, 0);
SendMessage(hCtrl4_0, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_1 = CreateWindowEx(0, WC_TREEVIEW, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | TVS_HASBUTTONS | TVS_HASLINES | TVS_LINESATROOT | TVS_DISABLEDRAGDROP | TVS_SHOWSELALWAYS | TVS_CHECKBOXES | TVS_FULLROWSELECT, 11, 11, 255, 364, hwnd, (HMENU)IDC_MODLIST, hInst, 0);
SendMessage(hCtrl4_1, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_2 = CreateWindowEx(0, WC_BUTTON, ("Load Mod..."), WS_VISIBLE | WS_CHILD | WS_TABSTOP, 12, 385, 75, 23, hwnd, (HMENU)IDLOAD, hInst, 0);
SendMessage(hCtrl4_2, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_3 = CreateWindowEx(0, WC_BUTTON, ("Remove Mod"), WS_VISIBLE | WS_CHILD | WS_TABSTOP, 96, 385, 75, 23, hwnd, (HMENU)IDREMOVE, hInst, 0);
SendMessage(hCtrl4_3, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_4 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 341, 151, 174, 20, hwnd, (HMENU)IDC_NAME, hInst, 0);
SendMessage(hCtrl4_4, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_5 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 341, 177, 174, 20, hwnd, (HMENU)IDC_AUTHOR, hInst, 0);
SendMessage(hCtrl4_5, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_6 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 341, 202, 174, 20, hwnd, (HMENU)IDC_TYPE, hInst, 0);
SendMessage(hCtrl4_6, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_7 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 341, 228, 174, 20, hwnd, (HMENU)IDC_VERSION, hInst, 0);
SendMessage(hCtrl4_7, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_8 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_VSCROLL | WS_BORDER | ES_AUTOHSCROLL | ES_MULTILINE | ES_READONLY, 341, 255, 174, 70, hwnd, (HMENU)IDC_DESC, hInst, 0);
SendMessage(hCtrl4_8, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_9 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 341, 330, 152, 20, hwnd, (HMENU)IDC_EXESPACE, hInst, 0);
SendMessage(hCtrl4_9, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_10 = CreateWindowEx(0, WC_BUTTON, ("..."), WS_VISIBLE | WS_CHILD | WS_TABSTOP, 497, 330, 17, 20, hwnd, (HMENU)IDC_EXEMORE, hInst, 0);
SendMessage(hCtrl4_10, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_11 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL | ES_READONLY, 341, 356, 152, 20, hwnd, (HMENU)IDC_DISKSPACE, hInst, 0);
SendMessage(hCtrl4_11, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_12 = CreateWindowEx(0, WC_BUTTON, ("..."), WS_VISIBLE | WS_CHILD | WS_TABSTOP, 497, 356, 17, 20, hwnd, (HMENU)IDC_DISKMORE, hInst, 0);
SendMessage(hCtrl4_12, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_13 = CreateWindowEx(WS_EX_TRANSPARENT, WC_STATIC, (""), WS_VISIBLE | WS_CHILD | SS_ETCHEDFRAME | SS_CENTERIMAGE | SS_REALSIZEIMAGE, 275, 11, 240, 130, hwnd, (HMENU)IDC_PREVIEW, hInst, 0);
SendMessage(hCtrl4_13, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_14 = CreateWindowEx(0, WC_STATIC, ("Name"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 275, 154, 56, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_14, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_15 = CreateWindowEx(0, WC_STATIC, ("Author"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 275, 180, 33, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_15, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_16 = CreateWindowEx(0, WC_STATIC, ("Type"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 275, 205, 26, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_16, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_17 = CreateWindowEx(0, WC_STATIC, ("Description"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 275, 255, 54, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_17, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_18 = CreateWindowEx(0, WC_STATIC, ("EXE Space"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 276, 332, 57, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_18, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_19 = CreateWindowEx(0, WC_STATIC, ("Disk Space"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 276, 359, 57, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_19, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl4_20 = CreateWindowEx(0, WC_STATIC, ("Version"), WS_VISIBLE | WS_CHILD | WS_GROUP | SS_LEFT, 275, 231, 36, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl4_20, WM_SETFONT, (WPARAM), FALSE);


wcex.style          = CS_HREDRAW | CS_VREDRAW;
wcex.lpfnWndProc    = DefWindowProc;
wcex.hInstance      = hInst;
wcex.hIcon          = LoadIcon(0, (LPCTSTR)IDI_APPLICATION);
wcex.hCursor        = LoadCursor(NULL, IDC_ARROW);
wcex.lpszClassName  = "WndClass5";
RegisterClassEx(&wcex);

HFONT hfont5 = CreateFont(-11, 0, 0, 0, 0, FALSE, FALSE, FALSE, 1, 0, 0, 0, 0, ("Ms Shell Dlg"));
HWND hwnd = CreateWindowEx(WS_EX_LEFT, ("WndClass")5, ("Patches for %file%"), WS_CAPTION | WS_VISIBLE | WS_POPUP | WS_SYSMENU, 0, 0, 306, 402, 0, 0, hInst, 0);
HWND hCtrl5_0 = CreateWindowEx(0, WC_LISTBOX, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_VSCROLL | WS_BORDER | LBS_DISABLENOSCROLL | LBS_NOINTEGRALHEIGHT | LBS_SORT | LBS_NOTIFY, 11, 11, 279, 163, hwnd, (HMENU)IDC_PATCHLIST, hInst, 0);
SendMessage(hCtrl5_0, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_1 = CreateWindowEx(0, WC_STATIC, ("Before"), WS_VISIBLE | WS_CHILD | SS_SIMPLE | SS_NOPREFIX, 11, 182, 33, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl5_1, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_2 = CreateWindowEx(0, WC_STATIC, ("After"), WS_VISIBLE | WS_CHILD | SS_SIMPLE | SS_NOPREFIX, 155, 182, 24, 15, hwnd, (HMENU)0, hInst, 0);
SendMessage(hCtrl5_2, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_3 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_VSCROLL | WS_BORDER | ES_AUTOHSCROLL | ES_MULTILINE | ES_READONLY, 11, 203, 137, 130, hwnd, (HMENU)IDC_PATCHPRE, hInst, 0);
SendMessage(hCtrl5_3, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_4 = CreateWindowEx(0, WC_EDIT, (""), WS_VISIBLE | WS_CHILD | WS_TABSTOP | WS_VSCROLL | WS_BORDER | ES_AUTOHSCROLL | ES_MULTILINE | ES_READONLY, 153, 203, 137, 130, hwnd, (HMENU)IDC_PATCHPOST, hInst, 0);
SendMessage(hCtrl5_4, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_5 = CreateWindowEx(0, WC_BUTTON, ("Hex"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | BS_LEFT | 0x00000009, 9, 346, 44, 13, hwnd, (HMENU)IDC_PATCHHEX, hInst, 0);
SendMessage(hCtrl5_5, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_6 = CreateWindowEx(0, WC_BUTTON, ("ASCII"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000009, 53, 346, 51, 13, hwnd, (HMENU)IDC_PATCHASCII, hInst, 0);
SendMessage(hCtrl5_6, WM_SETFONT, (WPARAM), FALSE);
HWND hCtrl5_7 = CreateWindowEx(0, WC_BUTTON, ("OK"), WS_VISIBLE | WS_CHILD | WS_TABSTOP | 0x00000001, 215, 340, 75, 23, hwnd, (HMENU)IDOK, hInst, 0);
SendMessage(hCtrl5_7, WM_SETFONT, (WPARAM), FALSE);


